In [1]:
import numpy as np

In [2]:
a = 1 + 1j
b = 1 - 1j

In [3]:
x = np.array([a, b])

In [4]:
def normalize(vector):
    def coeffLength(coeff):
        return np.real(coeff*np.conj(coeff))
    def totalLength():
        sum = 0
        for i in vector:
            sum += coeffLength(i)
        return sum**(0.5)
    totalSum = np.array(totalLength())
    return vector/totalSum

In [5]:
normalize(x)

array([0.5+0.5j, 0.5-0.5j])

In [6]:
#inner product, #outerproduct

In [7]:
def innerproduct(A, B):
    return B*np.matrix(A).getH()

In [8]:
innerproduct(x, x)

matrix([[4.+0.j]])

In [9]:
def outerproduct(A, B):
    return np.transpose(np.matrix(A).getH()*B)

In [10]:
outerproduct(x, x)

matrix([[2.+0.j, 0.+2.j],
        [0.-2.j, 2.+0.j]])

In [11]:
import qiskit