In [5]:
import numpy as np

In [6]:
a = 1 + 1j
b = 1 - 1j

In [7]:
x = np.array([a, b])

In [8]:
def normalize(vector):
    def coeffLength(coeff):
        return np.real(coeff*np.conj(coeff))
    def totalLength():
        sum = 0
        for i in vector:
            sum += coeffLength(i)
        return sum**(0.5)
    totalSum = np.array(totalLength())
    return vector/totalSum

In [9]:
normalize(x)

array([0.5+0.5j, 0.5-0.5j])

In [10]:
#inner product, #outerproduct

In [11]:
def inner(A, B):
    return A*np.matrix(B).getH()

In [12]:
inner(x, x)

matrix([[4.+0.j]])

In [15]:
def outer(A, B):
    return np.outer(A, B)

In [16]:
outer(x, x)

array([[0.+2.j, 2.+0.j],
       [2.+0.j, 0.-2.j]])

In [11]:
#linearly indep orthogonal

In [60]:
matrix = np.array(
    [
        [0, 1 ,5 ,20],
        [3, 0, 4, 15],
        [0, 1, 9, 36],
        [1, 7, 0, 0]
    ])

In [61]:
vectorA = np.array([1, 1j])
vectorB = np.array([1j, 1])

In [62]:
def isLinIndep(M):
    return (M.shape[1] == np.linalg.matrix_rank(M))

In [63]:
isLinIndep(matrix)

True

In [64]:
def isOrtho(A, B):
    return (innerproduct(A, B) == 0)

In [65]:
isOrtho(vectorA, vectorB)

matrix([[ True]])

In [66]:
#unitary, kroneckor product

In [40]:
M = np.array(
    [
        [1, 1],
        [1, -1]
    ])

In [36]:
def isUnitary(M):
    return np.allclose(np.eye(np.shape(M)[0]), np.matrix(M).getH()*M)

In [37]:
isUnitary(M)

False

In [41]:
def tensordot(A, B):
    return np.kron(A, B)

In [42]:
tensordot(M, M)

array([[ 1,  1,  1,  1],
       [ 1, -1,  1, -1],
       [ 1,  1, -1, -1],
       [ 1, -1, -1,  1]])