In [6]:
import numpy as np

In [7]:
a = 1 + 1j
b = 1 - 1j

In [8]:
x = np.array([a, b])

In [9]:
def normalize(vector):
    def coeffLength(coeff):
        return np.real(coeff*np.conj(coeff))
    def totalLength():
        sum = 0
        for i in vector:
            sum += coeffLength(i)
        return sum**(0.5)
    totalSum = np.array(totalLength())
    return vector/totalSum

In [10]:
normalize(x)

array([0.5+0.5j, 0.5-0.5j])

In [11]:
#inner product, #outerproduct

In [14]:
def innerproduct(A, B):
    return B*np.matrix(A).getH()

In [24]:
print(innerproduct(x, x))

[[4.+0.j]]


In [18]:
def outerproduct(A, B):
    return np.transpose(np.matrix(A).getH()*B)

In [19]:
outerproduct(x, x)

matrix([[2.+0.j, 0.+2.j],
        [0.-2.j, 2.+0.j]])

In [ ]:
#linearly indep orthogonal

In [103]:
matrix = np.array(
    [
        [0, 1 ,5 ,20, 6],
        [3, 0, 4, 15, 6],
        [0, 1, 9, 36, 6],
        [1, 7, 0, 0, 6]
    ])

In [98]:
vectorA = np.array([1, 1j])
vectorB = np.array([1j, 1])

In [99]:
def isLinIndep(M):
    return (M.shape[1] == np.linalg.matrix_rank(M))

In [100]:
isLinIndep(matrix)

True

In [101]:
def isOrtho(A, B):
    return (innerproduct(A, B) == 0)

In [102]:
isOrtho(vectorA, vectorB)

matrix([[ True]])